# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DATA MEETS PRODUCT
author:
  email: me@eliasnema.com
  twitter: eliasnema
  name: Elias Nema
description: >- # this means to ignore newlines until "baseurl:"
  Putting data to work: product analytics, personalisation and relevance, recommender systems and whatever is needed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eliasnema.com"
twitter_username: eliasnema
github_username:  eliasnema

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

excerpt_separator: ""
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..5

feed:
  categories:
    - newsletter

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: UA-165368106-1

twitter:
  username: eliasnema
  card: summary
