project:
  type: website

website:
  title: "ELIAS NEMA"
  site-url: https://www.eliasnema.com
  open-graph: true
  description: "Making data work: analytics, personalisation, relevance and recommender systems - whatever is takes."
  favicon: favicon.ico
  cookie-consent: true
  google-analytics:
    tracking-id: "UA-165368106-1"
    anonymize-ip: true
  twitter-card: true
  navbar:
    left:
      - text: "Data Feed"
        file: data-feed.qmd
      - blog.qmd
    right:
      - talks.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - lumen
      - custom.scss
    fontsize: 1.05em
    linestretch: 1.5
    fontcolor: "#567"
    mainfont: Roboto Mono, Courier, sans-serif
    max-width: 1000px
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    code-fold: true
    linkcolor: black
    include-in-header: <script type="text/javascript" src="node_modules/***/**.js"></script>
