"""Stage private research notebooks as generated Quarto inputs.

Normal renders do not include private articles. To preview the Router's Blind
Spot draft:

    INCLUDE_ROUTER_BLIND_SPOT_ARTICLE=1 quarto preview

Once the canonical notebook is no longer marked as a draft, use the same
environment variable with the normal render or publish command.

Set ROUTER_BLIND_SPOT_REPO to override the default sibling checkout at
../Research/router-blind-spot.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil


ENABLED_VALUES = {"1", "true", "yes", "on"}
ARTICLE_ENV = "INCLUDE_ROUTER_BLIND_SPOT_ARTICLE"
REPO_ENV = "ROUTER_BLIND_SPOT_REPO"
ARTICLE_RELATIVE_PATH = Path("article/index.ipynb")
STAGED_RELATIVE_PATH = Path("posts/router-blind-spot/index.ipynb")
MARKER_NAME = ".generated-from-private-research"


def project_root() -> Path:
    configured = os.environ.get("QUARTO_PROJECT_ROOT")
    if configured:
        return Path(configured).expanduser().resolve()
    return Path(__file__).resolve().parent.parent


def research_repo(root: Path) -> Path:
    configured = os.environ.get(REPO_ENV)
    if configured:
        return Path(configured).expanduser().resolve()
    return (root.parent / "Research" / "router-blind-spot").resolve()


def remove_previous_stage(destination: Path, marker: Path) -> None:
    if not marker.exists():
        return
    destination.unlink(missing_ok=True)
    marker.unlink(missing_ok=True)
    try:
        destination.parent.rmdir()
    except OSError:
        pass


def validate_notebook(source: Path) -> dict:
    try:
        notebook = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"Cannot read canonical article notebook: {error}") from error

    cells = notebook.get("cells", [])
    if not cells or cells[0].get("cell_type") != "raw":
        raise SystemExit("Canonical article must begin with a raw Quarto front-matter cell.")

    front_matter = "".join(cells[0].get("source", []))
    required_metadata = ("title:", "author:", "draft:")
    missing = [key for key in required_metadata if key not in front_matter]
    if missing:
        raise SystemExit(
            "Canonical article is missing Quarto front matter: " + ", ".join(missing)
        )

    code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
    if not code_cells or any(cell.get("execution_count") is None for cell in code_cells):
        raise SystemExit(
            "Canonical article must be executed and saved before it can be staged."
        )

    error_outputs = [
        output
        for cell in code_cells
        for output in cell.get("outputs", [])
        if output.get("output_type") == "error"
    ]
    if error_outputs:
        raise SystemExit("Canonical article contains an execution error.")

    serialized = json.dumps(notebook, ensure_ascii=False)
    if str(Path.home()) in serialized:
        raise SystemExit(
            "Canonical article contains an absolute path inside the user home directory."
        )

    return notebook


def main() -> None:
    root = project_root()
    destination = root / STAGED_RELATIVE_PATH
    marker = destination.parent / MARKER_NAME
    enabled = os.environ.get(ARTICLE_ENV, "").strip().lower() in ENABLED_VALUES

    if not enabled:
        remove_previous_stage(destination, marker)
        print(f"Private article staging disabled; set {ARTICLE_ENV}=1 to include it.")
        return

    source = research_repo(root) / ARTICLE_RELATIVE_PATH
    if not source.is_file():
        raise SystemExit(
            f"Canonical article not found at {source}. "
            f"Set {REPO_ENV} to the research checkout."
        )

    if destination.exists() and not marker.exists():
        raise SystemExit(
            f"Refusing to overwrite non-generated article at {destination}."
        )

    notebook = validate_notebook(source)
    notebook.setdefault("metadata", {})["generated_from_private_research"] = True

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(notebook, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    marker.write_text(
        "Generated by scripts/stage-private-articles.py; do not edit.\n",
        encoding="utf-8",
    )
    shutil.copystat(source, destination)
    print(f"Staged private Quarto article: {source} -> {destination}")


if __name__ == "__main__":
    main()
